# Generated by Django 5.0.2 on 2024-09-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_book_price_book_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='download',
        ),
        migrations.AddField(
            model_name='book',
            name='epub_file',
            field=models.FileField(blank=True, null=True, upload_to='epubs/'),
        ),
    ]
